language: rust
rust:
  - stable
  - nightly
os: linux
cache: cargo
jobs:
  include:
    - name: codecov
      rust: nightly
      before_install: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
      env:
        - CARGO_INCREMENTAL=0
        - RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        - RUSTDOCFLAGS="-Cpanic=abort"
      before_script: |
        find . \( -name "swc2dot*.gc*" \) -print0 | xargs -0 rm
      script:
        - cargo build --verbose $CARGO_OPTIONS
        - cargo test --verbose $CARGO_OPTIONS
        - |
          zip -0 ccov.zip `find . \( -name "swc2dot*.gc*" \) -print`;
          ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
          bash <(curl -s https://codecov.io/bash) -f lcov.info;
  allow_failures:
    - rust: nightly
  fast_finish: true
